# Generated by Django 3.0.7 on 2020-06-27 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20200627_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 27, 10, 1, 50, 68766, tzinfo=utc)),
        ),
    ]
